/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoReportRouteImport } from './routes/demo-report'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as JourneyCodeRouteImport } from './routes/journey.$code'
import { Route as AssessmentCodeRouteImport } from './routes/assessment.$code'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedResultsIdRouteImport } from './routes/_authenticated/results.$id'
import { Route as AuthenticatedProfileSafetyRouteImport } from './routes/_authenticated/profile.safety'
import { Route as AuthenticatedProfilePrivacyRouteImport } from './routes/_authenticated/profile.privacy'
import { Route as AuthenticatedProfileNotificationsRouteImport } from './routes/_authenticated/profile.notifications'
import { Route as AuthenticatedProfileHelpRouteImport } from './routes/_authenticated/profile.help'
import { Route as AuthenticatedJourneysIdRouteImport } from './routes/_authenticated/journeys.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPeachWebhookRouteImport } from './routes/api/public/peach.webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReportRoute = DemoReportRouteImport.update({
  id: '/demo-report',
  path: '/demo-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyCodeRoute = JourneyCodeRouteImport.update({
  id: '/journey/$code',
  path: '/journey/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCodeRoute = AssessmentCodeRouteImport.update({
  id: '/assessment/$code',
  path: '/assessment/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsIdRoute = AuthenticatedResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileSafetyRoute =
  AuthenticatedProfileSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePrivacyRoute =
  AuthenticatedProfilePrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileNotificationsRoute =
  AuthenticatedProfileNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileHelpRoute =
  AuthenticatedProfileHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedJourneysIdRoute = AuthenticatedJourneysIdRouteImport.update({
  id: '/journeys/$id',
  path: '/journeys/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPeachWebhookRoute = ApiPublicPeachWebhookRouteImport.update({
  id: '/api/public/peach/webhook',
  path: '/api/public/peach/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo-report': typeof DemoReportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/assessment/$code': typeof AssessmentCodeRoute
  '/journey/$code': typeof JourneyCodeRoute
  '/report/$token': typeof ReportTokenRoute
  '/journeys/$id': typeof AuthenticatedJourneysIdRoute
  '/profile/help': typeof AuthenticatedProfileHelpRoute
  '/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/profile/safety': typeof AuthenticatedProfileSafetyRoute
  '/results/$id': typeof AuthenticatedResultsIdRoute
  '/api/public/peach/webhook': typeof ApiPublicPeachWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo-report': typeof DemoReportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/assessment/$code': typeof AssessmentCodeRoute
  '/journey/$code': typeof JourneyCodeRoute
  '/report/$token': typeof ReportTokenRoute
  '/journeys/$id': typeof AuthenticatedJourneysIdRoute
  '/profile/help': typeof AuthenticatedProfileHelpRoute
  '/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/profile/safety': typeof AuthenticatedProfileSafetyRoute
  '/results/$id': typeof AuthenticatedResultsIdRoute
  '/api/public/peach/webhook': typeof ApiPublicPeachWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/demo-report': typeof DemoReportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/assessment/$code': typeof AssessmentCodeRoute
  '/journey/$code': typeof JourneyCodeRoute
  '/report/$token': typeof ReportTokenRoute
  '/_authenticated/journeys/$id': typeof AuthenticatedJourneysIdRoute
  '/_authenticated/profile/help': typeof AuthenticatedProfileHelpRoute
  '/_authenticated/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/_authenticated/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/_authenticated/profile/safety': typeof AuthenticatedProfileSafetyRoute
  '/_authenticated/results/$id': typeof AuthenticatedResultsIdRoute
  '/api/public/peach/webhook': typeof ApiPublicPeachWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo-report'
    | '/forgot-password'
    | '/guest'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/upgrade'
    | '/assessment/$code'
    | '/journey/$code'
    | '/report/$token'
    | '/journeys/$id'
    | '/profile/help'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/safety'
    | '/results/$id'
    | '/api/public/peach/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo-report'
    | '/forgot-password'
    | '/guest'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/upgrade'
    | '/assessment/$code'
    | '/journey/$code'
    | '/report/$token'
    | '/journeys/$id'
    | '/profile/help'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/safety'
    | '/results/$id'
    | '/api/public/peach/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/demo-report'
    | '/forgot-password'
    | '/guest'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/upgrade'
    | '/assessment/$code'
    | '/journey/$code'
    | '/report/$token'
    | '/_authenticated/journeys/$id'
    | '/_authenticated/profile/help'
    | '/_authenticated/profile/notifications'
    | '/_authenticated/profile/privacy'
    | '/_authenticated/profile/safety'
    | '/_authenticated/results/$id'
    | '/api/public/peach/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoReportRoute: typeof DemoReportRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuestRoute: typeof GuestRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AssessmentCodeRoute: typeof AssessmentCodeRoute
  JourneyCodeRoute: typeof JourneyCodeRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ApiPublicPeachWebhookRoute: typeof ApiPublicPeachWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-report': {
      id: '/demo-report'
      path: '/demo-report'
      fullPath: '/demo-report'
      preLoaderRoute: typeof DemoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$code': {
      id: '/journey/$code'
      path: '/journey/$code'
      fullPath: '/journey/$code'
      preLoaderRoute: typeof JourneyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$code': {
      id: '/assessment/$code'
      path: '/assessment/$code'
      fullPath: '/assessment/$code'
      preLoaderRoute: typeof AssessmentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$id': {
      id: '/_authenticated/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof AuthenticatedResultsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/safety': {
      id: '/_authenticated/profile/safety'
      path: '/safety'
      fullPath: '/profile/safety'
      preLoaderRoute: typeof AuthenticatedProfileSafetyRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/privacy': {
      id: '/_authenticated/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/notifications': {
      id: '/_authenticated/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AuthenticatedProfileNotificationsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/help': {
      id: '/_authenticated/profile/help'
      path: '/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof AuthenticatedProfileHelpRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/journeys/$id': {
      id: '/_authenticated/journeys/$id'
      path: '/journeys/$id'
      fullPath: '/journeys/$id'
      preLoaderRoute: typeof AuthenticatedJourneysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/peach/webhook': {
      id: '/api/public/peach/webhook'
      path: '/api/public/peach/webhook'
      fullPath: '/api/public/peach/webhook'
      preLoaderRoute: typeof ApiPublicPeachWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileHelpRoute: typeof AuthenticatedProfileHelpRoute
  AuthenticatedProfileNotificationsRoute: typeof AuthenticatedProfileNotificationsRoute
  AuthenticatedProfilePrivacyRoute: typeof AuthenticatedProfilePrivacyRoute
  AuthenticatedProfileSafetyRoute: typeof AuthenticatedProfileSafetyRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileHelpRoute: AuthenticatedProfileHelpRoute,
  AuthenticatedProfileNotificationsRoute:
    AuthenticatedProfileNotificationsRoute,
  AuthenticatedProfilePrivacyRoute: AuthenticatedProfilePrivacyRoute,
  AuthenticatedProfileSafetyRoute: AuthenticatedProfileSafetyRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedJourneysIdRoute: typeof AuthenticatedJourneysIdRoute
  AuthenticatedResultsIdRoute: typeof AuthenticatedResultsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedJourneysIdRoute: AuthenticatedJourneysIdRoute,
  AuthenticatedResultsIdRoute: AuthenticatedResultsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoReportRoute: DemoReportRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuestRoute: GuestRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AssessmentCodeRoute: AssessmentCodeRoute,
  JourneyCodeRoute: JourneyCodeRoute,
  ReportTokenRoute: ReportTokenRoute,
  ApiPublicPeachWebhookRoute: ApiPublicPeachWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
