-- Go-live safety containment.

-- Shared reports are served only by the token-validating server function.
-- Direct anonymous table access would allow enumeration of every enabled report.
DROP POLICY IF EXISTS "Public can read shared results" ON public.results;
REVOKE SELECT ON public.results FROM anon;

-- SMS bodies can contain OTPs, private notes, and report links. Remove existing
-- previews and keep future application writes metadata-only.
UPDATE public.sms_log SET content_preview = NULL WHERE content_preview IS NOT NULL;

-- Hosting-neutral rate-limit event storage for public and SMS-producing actions.
CREATE TABLE public.rate_limit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  key_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX rate_limit_events_lookup_idx
  ON public.rate_limit_events (action, key_hash, created_at DESC);
CREATE INDEX rate_limit_events_created_at_idx
  ON public.rate_limit_events (created_at);

ALTER TABLE public.rate_limit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.rate_limit_events FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.consume_rate_limit(
  action_name text,
  hashed_key text,
  window_seconds integer,
  max_events integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  recent_count integer;
BEGIN
  IF action_name IS NULL OR length(action_name) NOT BETWEEN 1 AND 80 THEN
    RAISE EXCEPTION 'invalid rate-limit action';
  END IF;
  IF hashed_key IS NULL OR length(hashed_key) <> 64 THEN
    RAISE EXCEPTION 'invalid rate-limit key';
  END IF;
  IF window_seconds NOT BETWEEN 1 AND 604800 OR max_events NOT BETWEEN 1 AND 1000 THEN
    RAISE EXCEPTION 'invalid rate-limit bounds';
  END IF;

  -- Serialize checks for the same action/key so parallel requests cannot all pass.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(action_name || ':' || hashed_key, 0)
  );

  -- Opportunistic bounded retention; no external scheduler is required.
  DELETE FROM public.rate_limit_events
  WHERE created_at < pg_catalog.now() - interval '7 days';

  SELECT count(*)::integer
  INTO recent_count
  FROM public.rate_limit_events
  WHERE action = action_name
    AND key_hash = hashed_key
    AND created_at >= pg_catalog.now() - pg_catalog.make_interval(secs => window_seconds);

  IF recent_count >= max_events THEN
    RETURN false;
  END IF;

  INSERT INTO public.rate_limit_events (action, key_hash)
  VALUES (action_name, hashed_key);
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_rate_limit(text, text, integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_rate_limit(text, text, integer, integer)
  TO service_role;
