-- Consent-led, privacy-safe marketing funnel events.
-- No user identifiers, IP addresses, paths, free text, or product content.
CREATE TABLE public.marketing_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name text NOT NULL CHECK (
    event_name IN ('landing_viewed', 'signup_started', 'signup_completed', 'core_action_completed')
  ),
  environment text NOT NULL CHECK (environment IN ('staging', 'production')),
  session_id uuid NOT NULL,
  flow text NOT NULL CHECK (flow IN ('landing', 'account', 'guest')),
  utm_source text CHECK (utm_source IN ('tiktok', 'instagram', 'threads', 'youtube')),
  utm_medium text CHECK (utm_medium = 'organic_social'),
  utm_campaign text CHECK (utm_campaign ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
  utm_content text CHECK (utm_content ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (environment, session_id, event_name, flow)
);

CREATE INDEX marketing_events_occurred_at_idx ON public.marketing_events (occurred_at DESC);
CREATE INDEX marketing_events_funnel_idx
  ON public.marketing_events (environment, utm_campaign, event_name, occurred_at DESC);

ALTER TABLE public.marketing_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.marketing_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.marketing_events_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.marketing_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.marketing_events_id_seq TO service_role;

-- The initial four-week pilot plus its seven-day review window needs no more
-- than 35 days of event history. Cleanup runs whenever a new event is stored.
CREATE OR REPLACE FUNCTION public.trim_marketing_events()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  DELETE FROM public.marketing_events
  WHERE occurred_at < pg_catalog.now() - interval '35 days';
  RETURN NEW;
END;
$$;

CREATE TRIGGER trim_marketing_events_after_insert
AFTER INSERT ON public.marketing_events
FOR EACH STATEMENT EXECUTE FUNCTION public.trim_marketing_events();

REVOKE ALL ON FUNCTION public.trim_marketing_events() FROM PUBLIC, anon, authenticated;
