ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'Master';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'slave';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'brat';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'little';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'pet';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'caregiver';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'primal';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'sadist';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'masochist';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'rope top';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'rope bottom';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'service top';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'service bottom';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'degradation giver';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'degradation receiver';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'exhibitionist';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'voyeur';

ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'Master';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'slave';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'brat';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'little';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'pet';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'caregiver';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'primal';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'sadist';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'masochist';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'rope top';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'rope bottom';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'service top';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'service bottom';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'degradation giver';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'degradation receiver';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'exhibitionist';
ALTER TYPE public.participant_type ADD VALUE IF NOT EXISTS 'voyeur';